### ISSUE TITLE
specify profile

### ISSUE THREAD

**Issue by RossHathaway** [aws/aws-encryption-sdk-cli#192]
I do not have a default profile specified in my .aws/config file. I tried running 
```
aws-encryption-cli --encrypt \
                     --input encryption-test.txt \
                     --wrapping-keys key=$KEY_ARN \
                     --metadata-output metadata \
                     --commitment-policy require-encrypt-require-decrypt \
                     --output encrypted
```
This resulted in an error: 
```Encountered unexpected error: increase verbosity to see details.
NoCredentialsError("Unable to locate credentials")
```

I tried setting environment variables to specify the account info to use:
`AWS_ACCESS_KEY_ID=BLAHBLAH12345`, `AWS_SECRET_ACCESS_KEY=BLOOBLOO678910` 
Then ran same command:
```
aws-encryption-cli --encrypt \                                
                     --input encryption-test.txt \ 
                     --wrapping-keys key=$KEY_ARN \
                     --metadata-output metadata \                         
                     --commitment-policy require-encrypt-require-decrypt \
                     --output encrypted
```
Then I tried making a default profile in my .aws/config that had the same access key id and secret access key I used for the environment variables, and the command worked. Is there something I need to do to tell the cli tool to use environment variables?

**Comment by farleyb-amazon** [comment]
Hi,

I haven't been able to reproduce your issue. What platform are you using, and how are you setting the environment variables?

You don't have to do anything special to tell the CLI tool to use environment variables. When I remove my default profile and unset my environment variables I get the same `NoCredentialsError` as you did. But when I then set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables I am successfully able to run the command. Here's what I'm running on a mac:

```
> unset AWS_ACCESS_KEY_ID    
> unset AWS_SECRET_ACCESS_KEY
> aws-encryption-cli --encrypt \
                     --input encryption-test.txt \
                     --wrapping-keys key=$KEY_ARN \
                     --metadata-output metadata \
                     --commitment-policy require-encrypt-require-decrypt \
                     --output encrypted

2020-11-09 11:48:10,977 - MainThread - aws_encryption_sdk_cli - WARNING - Operation failed: deleting output file: encrypted
Encountered unexpected error: increase verbosity to see details.
NoCredentialsError("Unable to locate credentials")
```

Followed by:
```
> export AWS_ACCESS_KEY_ID=<removed>                        
> export AWS_SECRET_ACCESS_KEY=<removed>
> aws-encryption-cli --encrypt \                                       
                     --input encryption-test.txt \
                     --wrapping-keys key=$KEY_ARN \
                     --metadata-output metadata \
                     --commitment-policy require-encrypt-require-decrypt \
                     --output encrypted

> base64 -i encrypted 
AgV4LcU+9pCIq8taowDfNQEYbPlQEO0/...
```

**Comment by RossHathaway** [comment]
Thanks FarleyB! Sorry I have missed your comment until now. I will try again in the next few days.

**Comment by RossHathaway** [comment]
Just thought to mention I was getting an error after having fixed the original issue, but it went away on its own after several hours:
```
An error occurred (InvalidSignatureException) when calling the GenerateDataKey operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```
May not be related to this cli tool, but just wanted to include in case others searching here find it useful.
