### ISSUE TITLE
Commitment Policy controls show incorrect values in helpstring

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-cli#227]
### Problem:

When the helpstring displays, the options shown for `--commitment-policy` are not the values that the CLI accepts as input.

```
  --commitment-policy {CommitmentPolicyArgs.FORBID_ENCRYPT_ALLOW_DECRYPT,CommitmentPolicyArgs.REQUIRE_ENCRYPT_ALLOW_DECRYPT,CommitmentPolicyArgs.REQUIRE_ENCRYPT_REQUIRE_DECRYPT}
                        Specifies the commitment policy for key commitment. ex: --commitment-policy=forbid-encrypt-allow-decrypt
```

### Solution:

`CommitmentPolicyArgs` defines a `str` method: this should be `__str__`

https://github.com/aws/aws-encryption-sdk-cli/blob/582d103673175a89a989a4b0b82ba7b50a520a47/src/aws_encryption_sdk_cli/internal/arg_parsing.py#L616-L625

I would also suggest adding a section to the readme docs that talks about commitment policy and points to the ESDK migration docs.

**Comment by farleyb-amazon** [comment]
Hey Matt, thanks for the suggestions. I've just cut https://github.com/aws/aws-encryption-sdk-cli/pull/228 which incorporates them. Closing this out, but please let us know if you find any other issues.
